/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: any;
            header?: any;
            path?: any;
            cookie?: any;
        };
        get?: any;
        put?: any;
        /** Sign up a new user */
        post: {
            parameters: {
                query?: any;
                header?: any;
                path?: any;
                cookie?: any;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description Create User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: any;
        options?: any;
        head?: any;
        patch?: any;
        trace?: any;
    };
}
export type webhooks = Record<string, any>;
export interface components {
    schemas: {
        User: {
            name?: string;
            phone?: string;
            password?: string;
        };
    };
    responses: any;
    parameters: any;
    requestBodies: any;
    headers: any;
    pathItems: any;
}
export type $defs = Record<string, any>;
export type operations = Record<string, any>;
